### ISSUE TITLE
does cron task need to run every minute?

### ISSUE THREAD

**Issue by danmarsden** [lmscloud-io/moodle-tool_vault#1]
https://github.com/lmscloud-io/moodle-tool_vault/blob/main/db/tasks.php#L32

should the default be to run this hourly or every 5 minutes rather than every minute?

feel free to close if it does need to be run this frequently - just something I usually double check when reviewing plugins.

**Comment by lmscloud-io** [comment]
Yes, because it emulates the adhoc tasks functionality inside itself, since it can not rely on adhoc tasks being present in the database (it will be wiped during restore). So basically it runs every minute, checks if its own queue is empty and exits. 

```
Execute scheduled task: Vault - Site migration (tool_vault\task\cron_task)
... started 17:53:49. Current memory use 71.1 MB.
... used 1 dbqueries
... used 0.00071191787719727 seconds
Scheduled task complete: Vault - Site migration (tool_vault\task\cron_task)
```

**Comment by danmarsden** [comment]
cool - I figured that was probably the case, but is something I usually try to check during a review :-)
