### ISSUE TITLE
How long will it take to finish a backup?

### ISSUE THREAD

**Issue by coolrobby** [lmscloud-io/moodle-tool_vault#11]
![微信截图_20240913145939](https://github.com/user-attachments/assets/ae026807-d5e9-408a-ac28-2c2391143912)
How long will it take to backup a Moodle site, which is about 500 m. It seems take a very long time.

**Comment by marinaglancy** [comment]
Hello. It depends on a lot of factors but it generally should be about 5-10 minutes. If your backup looks like it's stuck, there's a high chance that your cron job timed out. 
Try running backup from the CLI instead

**Comment by coolrobby** [comment]
Wow, thank you for your reply! That's a huge surprise! I got your reply! It has been almost 20 hours now, and I don't even know how to stop it. OK, I will try......

**Comment by coolrobby** [comment]
By the way, do you have a detailed tutorial? I will be very appreciated, since I don't think I have enough knowledge about that to handle it.

**Comment by marinaglancy** [comment]
Hello Robby
What exactly would you like to see in the tutorial?

Can you tell me about your current setup please:
Where do you host your Moodle site, do you have access to the terminal? Who
set up Moodle cron for you? Do you know how to run php CLI commands from
terminal?

By the way, there's a documentation page in Moodle docs how to run commands
from CLI:
https://docs.moodle.org/en/Administration_via_command_line

For vault backup you can cd to your Moodle folder and run:

sudo -u apache php admin/tool/vault/cli/site_backup.php --help

You might need to substitute 'apache' with you www user (for example
www-data) in this command

regards
Marina

**Comment by coolrobby** [comment]
Hello Marina,

I host my Moodle in my VPS and I think I have access to the terminal. I set up the Moodle site by myself and I have no idea what Moodle cron is. But now, I know what I should learn now. 

Thank you very much. Your instruction is very useful, it is exactly what I would like to see in the tutorial. It may take some days for me to learn what you mentioned in your instruction. Thank you!

Regards
Robby

**Comment by coolrobby** [comment]
It works in my another Moodle site hosted in Hostinger. Mybe there is something wrong with the cron in previous Moodle site.
![backup](https://github.com/user-attachments/assets/dc778976-6484-4083-8834-708f812a9955)

**Comment by coolrobby** [comment]
It works in my another Moodle site hosted in Hostinger. Mybe there is something wrong with the cron in previous Moodle site.

[13/09/24, 12:18:05] [info] [pid 667874] Backup pre-check: Database modifications...
[13/09/24, 12:18:06] [info] [pid 667874] ...OK
[13/09/24, 12:18:06] [info] [pid 667874] Backup pre-check: Disk space...
[13/09/24, 12:18:07] [info] [pid 667874] ...OK
[13/09/24, 12:18:07] [info] [pid 667874] Backup pre-check: Config overrides...
[13/09/24, 12:18:07] [info] [pid 667874] ...OK
[13/09/24, 12:18:07] [info] [pid 667874] Starting database backup
[13/09/24, 12:18:09] [info] [pid 667874] Uploading file dbdump.zip (380.0 KB)...
[13/09/24, 12:18:14] [info] [pid 667874] ...done
[13/09/24, 12:18:14] [info] [pid 667874] Uploading file dbstructure.zip (42.7 KB)...
[13/09/24, 12:18:17] [info] [pid 667874] ...done
[13/09/24, 12:18:17] [info] [pid 667874] Finished database backup
[13/09/24, 12:18:17] [info] [pid 667874] Starting dataroot backup
[13/09/24, 12:18:17] [info] [pid 667874] Uploading file dataroot.zip (2.0 MB)...
[13/09/24, 12:18:20] [info] [pid 667874] ...done
[13/09/24, 12:18:20] [info] [pid 667874] Finished dataroot backup
[13/09/24, 12:18:20] [info] [pid 667874] Starting files backup
[13/09/24, 12:18:20] [info] [pid 667874] Uploading file filedir.zip (2.4 MB)...
[13/09/24, 12:18:23] [info] [pid 667874] ...done
[13/09/24, 12:18:23] [info] [pid 667874] Finished files backup, 10 files exported
[13/09/24, 12:18:23] [info] [pid 667874] Total size of backup: 4.8 MB
[13/09/24, 12:18:24] [info] [pid 667874] Backup finished
[Return to the site](https://moodle.tkykt.site/)

**Comment by coolrobby** [comment]
Hello Marina,

Sorry to bother you again.

I backed up successfully. But..... It keeps sticking at 49%. I used SSH to perform the backup and ran cron to restore. How can I terminate this restore process and use SSH to retry it?

[u440484959@id-dci-web1417 domains]$ cd md.tkykt.site
[u440484959@id-dci-web1417 md.tkykt.site]$ sudo -u httpd php admin/tool/vault/cli/site_restore.php
-bash: sudo: command not found
Your reply will be highly appreciated.

Regards,
Robby

**Comment by marinaglancy** [comment]
Hello @coolrobby 
Regular cron is essential for running Moodle. You can find more information on https://docs.moodle.org/404/en/Cron

Make sure to execute CLI commands with --help argument first to see the usage instructions. If `sudo` command is not available to you, try running without it but it may create files with the wrong permissions and your website will not be able to work with them: `php admin/tool/vault/cli/site_restore.php --help`

If your restore process got stuck in the middle of the DB restore stage, unfortunately, your site can not be recovered and you need to reinstall Moodle and repeat restore. If your restore process got stuck AFTER the db restore stage, you can try to repeat it. 

I don't know why `sudo` command is absent on your server. I'm sorry I'm not in a position to educate on how to use CLI, cron and execute commands as the web user. Also it depends on what operating system you use and I don't know what you have. This is not related to the tool_vault, it is a general knowledge and there should be a lot of resources available in internet.

Good luck.

**Comment by coolrobby** [comment]
Hello Marina,

Thank you for your patience.

It's OK now! The backup and restore are successful!

Regards,
Robby

**Comment by coolrobby** [comment]
Hello Marina,
I have successfully completed the backup and noticed a problem, though I'm not sure if it's just my case. The progress bar during the backup restoration seems to get stuck, but actually, there's no need to worry about it; it should complete in about 2 hours. I have another question: I want to upgrade from Moodle 3.11.11 to 4.4, but it seems that backups from 3.11.11 cannot be restored directly in 4.4. Is there any solution for this？
Regards,
Robby

**Comment by marinaglancy** [comment]
You need to check "Automatically upgrade Moodle after restore" in the settings. I think you have already did it, otherwise the restore pre-check would prevent the restore process. I can see in the server logs that you have started restore process but it was never finished and there was no error reported. 

I suppose it means that the error happened at some point during your restore that terminated the process on your side but did not notify the server. 

Would it be possible for you to try to repeat the restore using CLI so you can see all errors on the screen and show me the log?

**Comment by coolrobby** [comment]
OK, I will restore it using CLI. But it takes some time. Because I am not very familiar with it.

**Comment by lmscloud-io** [comment]
Hello! There have been several important improvements in tool_vault since you reported this issue. For the full list of changes please refer to the CHANGELOG : https://github.com/lmscloud-io/moodle-tool_vault/blob/main/CHANGELOG.md

Some important changes that may help in your situation:

```
- Pre-check for both backup and restore checking the PHP setting max_execution_time.
  Fail if it is under one hour, warn if it has a limit.
- Shutdown handler to detect if the process was interrupted.
- Capture all output and show in the vault log.
- Improved warning message about operation timeout and restoring access to the site.
```

Basically there is not much we can do if there is a strict time limit for cron processes on your server. However we tried to improve logging - warn if the timeout is set, try to detect if the process was terminated, adding a warning message that it is likely that the process timeout, etc.

Hope it helps!
