### ISSUE TITLE
Hardcoded strings

### ISSUE THREAD

**Issue by dinism** [lmscloud-io/moodle-tool_vault#14]
I'm PT-PT translator.
In page, I have an API key, the "API key" is hardcoded to english.

The string in AMOS loginexplanation | tool_vault
Create an account on {\$a} to be able to backup or restore the site. 
{\$a} should be {\$a} to show _https://lmsvault.io_

**Comment by marinaglancy** [comment]
Thanks for the report. I'm going to add a workaround for the second problem you mentioned but it looks like a problem in how AMOS imports plugin strings, I reported it here https://tracker.moodle.org/browse/MDLSITE-7810

**Comment by marinaglancy** [comment]
This was fixed in version 2.5 released today.
Obrigada.

**Comment by dinism** [comment]
Translation completed. Thanks for the plugin.

MUITO OBRIGADO. Açores
