### ISSUE TITLE
Mark restore as finished before running core upgrade process

### ISSUE THREAD

**Issue by marinaglancy** [lmscloud-io/moodle-tool_vault#16]
When "automatically upgrade" option is selected, tool_vault launches Moodle upgrade after restore is completed.

It will execute all legacy steps first and then run the normal upgrade. For example, when upgrading from 3.9 to 4.3, tool_vault will run it's own upgrade steps to upgrade to 3.11.8 and then pass it to the core to upgrade from 3.11.8 to 4.3.x

Any error that happens during the "legacy" upgrade is tracked and reported. Errors that happens during the "normal" upgrade are not caught. 

When the "legacy" upgrade finished, the restore process should be considered finished. Site can be taken out of tool_vault maintenance mode (and set 'upgraderunning') and the restore should be reported to the server as successfully completed. 

Any upgrade error that happens after that is outside of the tool_vault control and does not mean that the restore failed. 

Also investigate, why the error that happens during upgrade is not caught/reported by tool_vault

**Comment by lmscloud-io** [comment]
I'm going to close this issue as won't fix. The restore will still be marked as failed if the upgrade process failed. However there were several other improvements in version  2.7 that can help here.

First of all, apparently the core upgrade process calls `die(1)'` if there is an exception, which also terminates the cron process if we invoked the upgrade from the tool vault. We added a shutdown handler and, at least, the restore is immediately marked as failed and does not show "Operation timed out".

Second, vault will now capture full output and add it to the logs. So the vault log will now show what went wrong. And finally, developer debugging is forced, so logs will contain a lot of details.
