### ISSUE TITLE
missing external_location_link part of privacy api

### ISSUE THREAD

**Issue by danmarsden** [lmscloud-io/moodle-tool_vault#3]
This plugin ships user data to an external system so should really be implementing the external_location_link component of the privacy api
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

this is typically a blocker for plugins db approval

**Comment by lmscloud-io** [comment]
Thanks for pointing it out, Dan!

This is how it appears in the "Plugin privacy compliance registry" now:

![privacy](https://github.com/lmscloud-io/moodle-tool_vault/assets/128620190/c3b5004d-aee9-4d19-9196-f759f0c097dc)

**Comment by danmarsden** [comment]
cool - I think this was the only blocker - so as soon as you're ready, just upload the new version to the plugins db and hit the request re-approval button (and ping me as well, as re-approval doesn't trigger any notifications) and I'll go back and approve the plugins db entry!

**Comment by lmscloud-io** [comment]
I was waiting for GHA to finish and then forgot to push. Version 1.1 is uploaded to the plugins directory now. Thanks for review, Dan.
